// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetShelter.DataAccessLayer;

#nullable disable

namespace PetShelter.DataAccessLayer.Migrations
{
    [DbContext(typeof(PetShelterContext))]
    [Migration("20230306135841_FinalMigration")]
    partial class FinalMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetShelter.DataAccessLayer.Models.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DonorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonorId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("PetShelter.DataAccessLayer.Models.Fundraiser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 3, 6, 15, 58, 40, 936, DateTimeKind.Local).AddTicks(1422));

                    b.Property<decimal>("DonationAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("DueDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 4, 5, 15, 58, 40, 936, DateTimeKind.Local).AddTicks(856));

                    b.Property<decimal>("GoalValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Active");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Fundraisers");
                });

            modelBuilder.Entity("PetShelter.DataAccessLayer.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FundraiserWhichGotTheDonationId")
                        .HasColumnType("int");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("FundraiserWhichGotTheDonationId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("PetShelter.DataAccessLayer.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdopterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsHealthy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsSheltered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("RescuerId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("WeightInKg")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AdopterId");

                    b.HasIndex("RescuerId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("PetShelter.DataAccessLayer.Models.Donation", b =>
                {
                    b.HasOne("PetShelter.DataAccessLayer.Models.Person", "Donor")
                        .WithMany("Donations")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("PetShelter.DataAccessLayer.Models.Fundraiser", b =>
                {
                    b.HasOne("PetShelter.DataAccessLayer.Models.Person", "Owner")
                        .WithMany("OwnedFundraisers")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PetShelter.DataAccessLayer.Models.Person", b =>
                {
                    b.HasOne("PetShelter.DataAccessLayer.Models.Fundraiser", "FundraiserWhichGotTheDonation")
                        .WithMany("Donors")
                        .HasForeignKey("FundraiserWhichGotTheDonationId");

                    b.Navigation("FundraiserWhichGotTheDonation");
                });

            modelBuilder.Entity("PetShelter.DataAccessLayer.Models.Pet", b =>
                {
                    b.HasOne("PetShelter.DataAccessLayer.Models.Person", "Adopter")
                        .WithMany("AdoptedPets")
                        .HasForeignKey("AdopterId");

                    b.HasOne("PetShelter.DataAccessLayer.Models.Person", "Rescuer")
                        .WithMany("RescuedPets")
                        .HasForeignKey("RescuerId");

                    b.Navigation("Adopter");

                    b.Navigation("Rescuer");
                });

            modelBuilder.Entity("PetShelter.DataAccessLayer.Models.Fundraiser", b =>
                {
                    b.Navigation("Donors");
                });

            modelBuilder.Entity("PetShelter.DataAccessLayer.Models.Person", b =>
                {
                    b.Navigation("AdoptedPets");

                    b.Navigation("Donations");

                    b.Navigation("OwnedFundraisers");

                    b.Navigation("RescuedPets");
                });
#pragma warning restore 612, 618
        }
    }
}
